[project]
name = "brave-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.12.3",
    "logging>=0.4.9.6",
    "streamlit>=1.49.1",
]
